name: bundle-sdk
on: { push: { branches: [main] } }
permissions: { contents: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - run: npm ci              # ① 依存を node_modules に展開

      - run: |
          echo "import * as S from '@kuru-labs/kuru-sdk'; export default S;" > sdk-entry.js
          echo "export default () => ({to:'0x116a9f35a402a2d34457bd72026c7f722d9d6333',gasLimit:700000});" > tx-stub.js

      - run: |                   # ② 単一エントリ + --packages=bundle
          npx esbuild sdk-entry.js \
            --bundle --format=iife --global-name=KuruSdk \
            --alias:src/utils/txConfig=./tx-stub.js \
            --packages=bundle \
            --minify --outfile=docs/kuru-sdk.browser.js

      - run: |                   # ③ 差分コミット
          git diff --quiet docs/kuru-sdk.browser.js && exit 0
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add docs/kuru-sdk.browser.js
          git commit -m "ci: bundle sdk"
          git push
