name: bundle-sdk
on: [push]                     # ← ユーザー Mint では動かない
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: { node-version: '18' }

    - name: bundle
      run: |
        npm install @kuru-labs/kuru-sdk@latest esbuild@latest
        # SDKがこれらを上書きすることを期待
        echo "export default () => ({to:'0x116a9f35a402a2d34457bd72026c7f722d9d6333',gasLimit:700000,gasPrice:0,nonce:0});" > tx-stub.js
        npx esbuild node_modules/@kuru-labs/kuru-sdk/dist/index.js \
          --bundle --format=iife --global-name=KuruSdk \
          --alias:src/utils/txConfig=./tx-stub.js \
          --minify --outfile=docs/kuru-sdk.browser.js

    - name: commit
      run: |
        git config user.name  github-actions
        git config user.email github-actions@github.com
        git add docs/kuru-sdk.browser.js
        git commit -m "ci: bundle sdk" || echo "no changes"
        git push
