name: bundle
on: { push: { branches: [main] } }
permissions: { contents: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20            # Node18 は EoL

      - run: npm install --no-audit --no-fund   # 依存展開

      - run: |
          echo "import * as S from '@kuru-labs/kuru-sdk'; import * as ethers from 'ethers'; window.KuruSdk=S; window.ethers=ethers;" > sdk-entry.js
          npx esbuild sdk-entry.js \
            --bundle \
            --format=iife \
            --global-name=KuruSdk \
            --define:global=this \
            --define:require=undefined \
            --tree-shaking=false \
            --minify \
            --outfile=docs/kuru-sdk.browser.js

      - name: Commit docs if changed
        run: |
          if ! git diff --quiet docs; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add docs package-lock.json
            git commit -m "ci: bundle sdk"
            git push
          fi
